### ISSUE TITLE
** (UndefinedFunctionError) function Poison.decode!/1 is undefined (module Poison is not available)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#1]
While trying to decode a JSON file using Poison https://github.com/devinus/poison
seeing:
```
 1) HashTest: failure on setup_all callback, test invalidated
     ** (UndefinedFunctionError) function Poison.decode!/1 is undefined (module Poison is not available)
     stacktrace:
       Poison.decode!("{\n  \"3SsqzMWq\": \"eWVH8kBYSD\",\n  \"eWVH8kBY\": \"TeeyDAQ4CB\",\n  \"TeeyDAQ4\": \"mmM1jDFSVq\",\n }\n")
       test/hash_test.exs:11: HashTest.__ex_unit_setup_all_0/1
       test/hash_test.exs:1: HashTest.__ex_unit__/2
```

**Comment by nelsonic** [comment]
Tried:
```
  require Poison
```
but got:
```
** (CompileError) test/hash_test.exs:3: module Poison is not loaded and could not be found
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/code.ex:376: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:59: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

**Comment by nelsonic** [comment]
Tried adding to `applications: [:poison],` in `mix.exs` but got:
```
** (Mix) Could not start application poison: could not find application file: poison.app
```

**Comment by nelsonic** [comment]
Tried in iex:
```
iex(1)> Poison.encode!(%{"age" => 27, "name" => "Devin Torres"})
```
got:
```
** (UndefinedFunctionError) function Poison.encode!/1 is undefined (module Poison is not available)
```
Don't _understand_ why ... 😕

**Comment by nelsonic** [comment]
This worked:  🙄 
```
alias Poison, as: JSON
```
