### ISSUE TITLE
Avoid Sending the Response *Twice* ... (Plug.Conn.AlreadySentError) the response was already sent

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#2]
```elixir
16:36:11.245 [error] #PID<0.285.0> running App.Router terminated
Server: localhost:8080 (http)
Request: GET /upload
** (exit) an exception was raised:
    ** (Plug.Conn.AlreadySentError) the response was already sent
        (plug) lib/plug/conn.ex:499: Plug.Conn.resp/3
        (plug) lib/plug/conn.ex:486: Plug.Conn.send_resp/3
        (app) lib/router.ex:1: App.Router.plug_builder_call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /dwyl/hits-elixir/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

**Comment by nelsonic** [comment]
This is no longer an issue because I'm not using this plug.
but it was solved by:
```elixir
  def call(conn, opts) do
    conn
    |> put_resp_content_type("image/svg+xml")
    |> send_resp(200, make_badge(42))
    |> halt()
  end
  
```
