### ISSUE TITLE
Setting Up Test Coverage

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits-elixir#4]
Trying to setup coverage for this project seeing:
![image](https://user-images.githubusercontent.com/194400/30239489-c94d446c-9555-11e7-9ece-9660cd44ead6.png)

```
** (Mix) The task "coveralls.json" could not be found
```
https://travis-ci.org/dwyl/hits-elixir/builds/273583142#L585

# _Solution_

The fix is making sure that `MIX_ENV=test` is set before attempting to run the command.
e.g:
```
MIX_ENV=test mix coveralls.json
```

On Travis CI this is:

https://github.com/dwyl/hits-elixir/blob/fdc29bd1c3cb49403f6fd3a7cc2ece9488be700b/.travis.yml#L4-L7

**Comment by nelsonic** [comment]
Next Error:
https://travis-ci.org/dwyl/hits-elixir/builds/273585456#L55
![image](https://user-images.githubusercontent.com/194400/30239683-05494750-955a-11e7-9f84-d9e881408438.png)

```elixir
131.95s$ mix local.rebar --force
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :etimedout}]}
Could not fetch rebar at:
    https://repo.hex.pm/installs/1.0.0/rebar-2.6.2
Please download the file above manually to your current directory and run:
    mix local.rebar rebar ./rebar
The command "mix local.rebar --force" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by nelsonic** [comment]
Restarted the build as it appears to be an _intermittent_ failure: https://github.com/elixir-lang/elixir/issues/5731

**Comment by nelsonic** [comment]
Now getting: https://travis-ci.org/dwyl/hits-elixir/builds/273585456#L698
![image](https://user-images.githubusercontent.com/194400/30240813-56af6cfe-956f-11e7-9acf-d1e228f3cb19.png)

Which is feedback I can _work_ with!
Looks like we have some tidying up to do! 🙄

**Comment by nelsonic** [comment]
https://travis-ci.org/dwyl/hits-elixir/builds/273652005#L751
![image](https://user-images.githubusercontent.com/194400/30242030-b35db84a-9586-11e7-9aac-1940946055e2.png)

```
 ** (ArgumentError) argument error
     code: conn = Router.call(conn, @opts)
     stacktrace:
       (kernel) :os.system_time(:millisecond)
       (app) lib/router.ex:86: App.Router.save_hit/1
       (app) lib/router.ex:25: App.Router.render_badge/1
       (app) lib/router.ex:1: App.Router.plug_builder_call/2
       test/router_test.exs:30: (test)

```

**Comment by nelsonic** [comment]
https://travis-ci.org/dwyl/hits-elixir/builds/273653331#L760
![image](https://user-images.githubusercontent.com/194400/30242106-21992ec4-9588-11e7-8f96-6dd1e1ae74fe.png)
```
(kernel) :os.system_time(:millisecond)
```

**Comment by nelsonic** [comment]
Coverage _almost_ there:
https://codecov.io/gh/dwyl/hits-elixir/compare/180c06b7124ff881bc5fc266f79bcde02b88ac97...c7acb497183bf8c0f6652ddeb95f616225405fb2/src/lib/router.ex?before=lib/router.ex#D1-62
![image](https://user-images.githubusercontent.com/194400/30242273-50b86316-958b-11e7-9d7f-58481bfa53f6.png)
